# Generated by Django 3.0.3 on 2020-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(default='My blog', max_length=64, verbose_name='Blog Header')),
                ('header_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Font color of header text')),
                ('header_text_font_size', models.CharField(default='20px', max_length=4, verbose_name='Font size of header text')),
                ('text_under_header', models.TextField(default='Text under header', verbose_name='Text under header')),
                ('text_under_header_font_color', models.CharField(default='Black', max_length=8, verbose_name="Font's color of text under header")),
                ('text_under_header_font_size', models.CharField(default='12px', max_length=8, verbose_name="Font's size of text under header")),
                ('first_paragraph_text', models.TextField(default='First paragraph text', verbose_name='First paragraph text')),
                ('first_paragraph_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Color of paragraph')),
                ('first_paragraph_text_font_size', models.CharField(default='12px', max_length=4, verbose_name='Size of paragraph')),
                ('second_paragraph_text', models.TextField(default='Second paragraph text', verbose_name='Second paragraph text')),
                ('second_paragraph_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Color of paragraph n2')),
                ('second_paragraph_text_font_size', models.CharField(default='Black', max_length=8, verbose_name='Size of paragraph n2')),
                ('third_paragraph_text', models.TextField(default='Third paragraph text', verbose_name='Third paragraph text')),
                ('third_paragraph_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Color of paragraph n3')),
                ('third_paragraph_text_font_size', models.CharField(default='Black', max_length=8, verbose_name='Size of paragraph n3')),
                ('second_header_text', models.CharField(default='Second header', max_length=64, verbose_name='Second Blog Header')),
                ('second_header_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Font color of second header text')),
                ('second_header_text_font_size', models.CharField(default='16px', max_length=4, verbose_name='Font size of second header text')),
                ('third_header_text', models.CharField(default='Third header', max_length=64, verbose_name='Third Blog Header')),
                ('third_header_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='Font color of third header text')),
                ('third_header_text_font_size', models.CharField(default='16px', max_length=4, verbose_name='Font size of third header text')),
                ('element1_list', models.TextField(default='1st element text', verbose_name='element1 text')),
                ('element2_list', models.TextField(default='2nd element text', verbose_name='element2 text')),
                ('element3_list', models.TextField(default='3rd element text', verbose_name='element3 text')),
                ('element4_list', models.TextField(default='4th element text', verbose_name='element4 text')),
                ('element5_list', models.TextField(default='5th element text', verbose_name='element5 text')),
                ('list_elements_font_color', models.CharField(default='Black', max_length=8, verbose_name='list color')),
                ('list_elements_font_size', models.CharField(default='12px', max_length=4, verbose_name='list size')),
                ('footer_1_paragraph_text', models.TextField(default='footer 1st paragraph', verbose_name='1st footer paragraph text')),
                ('footer_1_paragraph_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='1st footer paragraph color')),
                ('footer_1_paragraph_text_font_size', models.CharField(default='12px', max_length=4, verbose_name='1st footer paragraph font size')),
                ('footer_2_paragraph_text', models.TextField(default='footer 1st paragraph', verbose_name='2nd footer paragraph text')),
                ('footer_2_paragraph_text_font_color', models.CharField(default='Black', max_length=8, verbose_name='2nd footer paragraph font color')),
                ('footer_2_paragraph_text_font_size', models.CharField(default='12px', max_length=4, verbose_name='2nd footer paragraph font size')),
            ],
        ),
    ]
